import { createHash } from "node:crypto";
import { z } from "zod";
import { recordKey, METRIC_FIELDS, type UsageRecord } from "../../packages/protocol/records.mjs";
import type { UsageFact } from "@/lib/usage-display";

// A legacy row does not identify individual accounts. Therefore a cutover must
// cover an entire member/tool/day, including every reviewed account and device.
// These manifests are operator-installed only, never generated by ingestion.
export const cutoverSchema = z.object({
  version: z.literal(1),
  scopes: z.array(z.object({
    memberId: z.string().regex(/^[a-f\d]{24}$/i).transform((v) => v.toLowerCase()),
    tool: z.enum(["claude_code", "codex", "gemini", "grok", "opencode"]),
    date: z.iso.date(),
    accountIds: z.array(z.string().min(1)).min(1),
    deviceIds: z.array(z.string().min(1)).min(1),
    inventoryDigest: z.string().regex(/^[a-f\d]{64}$/),
    ledgerDigest: z.string().regex(/^[a-f\d]{64}$/),
    expectedCount: z.number().int().positive().safe(),
    registeredScopeReviewed: z.literal(true),
    reviewedAt: z.iso.datetime(),
  }).strict()),
}).strict();
export type CutoverScope = z.infer<typeof cutoverSchema>["scopes"][number];
export type LedgerEntry = { semantics: UsageRecord; digest: string };
export function ledgerDigest(entries: LedgerEntry[]): string {
  return createHash("sha256").update(JSON.stringify(entries.map((r) => [recordKey(r.semantics), r.digest]).sort((a, b) => a[0].localeCompare(b[0])))).digest("hex");
}
export function scopeKey(scope: { memberId: string; tool: string; date: string }): string {
  return JSON.stringify([scope.memberId, scope.tool, scope.date]);
}
export function cutoverBlockers(scope: CutoverScope, entries: LedgerEntry[], today: string, conflictCount: number): string[] {
  const blockers: string[] = [];
  if (scope.date >= today) blockers.push("open_or_future_day");
  if (entries.length !== scope.expectedCount || ledgerDigest(entries) !== scope.ledgerDigest) blockers.push("ledger_changed_or_incomplete");
  const accounts = [...new Set(entries.map((r) => r.semantics.accountId))].sort();
  if (JSON.stringify(accounts) !== JSON.stringify([...new Set(scope.accountIds)].sort())) blockers.push("account_scope_mismatch");
  if (entries.some((r) => r.semantics.identityQuality !== "native" || r.semantics.completeness !== "final")) blockers.push("unverified_source");
  const relevant = entries.filter(({ semantics: r }) => r.kind === "cumulative" || new Date(Date.parse(r.occurredAt) + 9 * 3600000).toISOString().slice(0, 10) === scope.date);
  if (relevant.some(({ semantics: r }) => METRIC_FIELDS.some((f) => !r.fieldEvidence?.[f] || r.fieldEvidence[f] === "unknown"))) blockers.push("source_metrics_unknown");
  if (conflictCount) blockers.push("unresolved_conflicts");
  return blockers;
}

export function replaceReviewedScopes(legacy: UsageFact[], replacements: Array<{ scope: CutoverScope; facts: UsageFact[]; blockers: string[] }>): UsageFact[] {
  const approved = replacements.filter((r) => !r.blockers.length);
  const keys = new Set(approved.map((r) => scopeKey(r.scope)));
  if (keys.size !== approved.length) throw Error("Duplicate cutover scope");
  // Remove precisely the approved local uploader scope. Provider reports,
  // unrelated people, unlinked rows and other days remain untouched.
  return [...legacy.filter((r) => r.source !== "uploader" || !keys.has(scopeKey(r))), ...approved.flatMap((r) => r.facts)];
}

// Query filters used by displayRows are deliberately narrow. An unfamiliar
// filter disables cutover rather than expanding access or losing a device view.
export function supportsCutoverMatch(match: Record<string, unknown>): boolean {
  return Object.entries(match).every(([field, v]) => ["date", "hour", "memberId", "tool"].includes(field) &&
    (!(v && typeof v === "object" && !("toHexString" in v)) || Object.keys(v).every((k) => ["$gte", "$lte", "$gt", "$lt", "$ne", "$in"].includes(k))));
}
export function matchesFact(fact: UsageFact, match: Record<string, unknown>): boolean {
  return Object.entries(match).every(([field, filter]) => {
    const value = String(fact[field as keyof UsageFact] ?? "");
    if (filter && typeof filter === "object" && !("toHexString" in filter)) return Object.entries(filter).every(([op, bound]) => {
      if (op === "$in") return Array.isArray(bound) && bound.some((v) => String(v) === value);
      if (op === "$ne") return bound === null ? value !== "" : value !== String(bound);
      if (op === "$gte") return value >= String(bound);
      if (op === "$lte") return value <= String(bound);
      if (op === "$gt") return value > String(bound);
      if (op === "$lt") return value < String(bound);
      return false;
    });
    return filter === null ? value === "" : value === String(filter);
  });
}
